### ISSUE TITLE
Crash on starting Rimworld

### ISSUE THREAD

**Issue by wengole** [SamboyCoding/RimworldBetterLoading#8]
I'm not sure what happened. I had this mod (and many others) all working fine. Decided to start a new colony with fewer mods so disabled a bunch and restarted, now the game won't start unless I unsubscribe from Better Loading in Steam

```
[BetterLoading] Finished stage Finalizing Mods at 7:51:57 PM.
[BetterLoading] Starting stage Running Post-Finalize Callbacks.
[BetterLoading] Finished calling static constructors at 7:51:57 PM. AND I didn't make the game freeze. Take that, Tynan.
Started post-finalize at 637427083190883430
[BetterLoading] Processing 2 post-finalize tasks.
OnLevelWasLoaded was found on ModInitializerComponent
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename: ./Runtime/Mono/MonoScriptCache.cpp Line: 355)

[BetterLoading] Finished stage Running Post-Finalize Callbacks at 7:51:59 PM.
[BetterLoading] Starting stage Initializing HugsLib.
[HugsLib] initializing HeatMap, RunAndGun, ImprovedWorkbenches, DefensivePositions, raceQuestPawn, PeteTimesSix.SimpleSidearms, CodeOptimist.JobsOfOpportunity, com.jkluch.HaulToStack, DeathRattle, MaterialFilter, LWM_DeepStorage, Hospitality
[BetterLoading:HugsLib Compat] HugsLib has enumerated child mods, it has found 13 of them.
Obtained 11 stack frames.
#0  0x00000041f6e4f7 in (Unknown)
#1  0x000000417dfdf0 in Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
#2  0x000000417dfdac in Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
#3  0x000000417df214 in System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
#4  0x007faa4a8e0389 in mono_print_method_from_ip
#5  0x007faa4aa4c167 in mono_perfcounter_foreach
#6  0x007faa4aa65df7 in mono_threads_set_shutting_down
#7  0x007faa4aac744f in GC_inner_start_routine
#8  0x007faa4aabc1ba in GC_call_with_stack_base
#9  0x007faab55b03e9 in start_thread
#10 0x007faab54de293 in clone
```

**Comment by SamboyCoding** [comment]
Wow ok, that's certainly unusual. Could you upload the full log file from one of these crashes somewhere? That doesn't tell me much, unfortunately.

**Comment by wengole** [comment]
Slightly different modlist, but re-enabled Better Loading today and it's still happening. Here's the full log

[rimworld_log_1000.txt](https://github.com/SamboyCoding/RimworldBetterLoading/files/5648537/rimworld_log_1000.txt)

**Comment by SamboyCoding** [comment]
I'm honestly not sure. There may be an incompatibility with Linux - I shall investigate, I have a Linux machine.

**Comment by MCOfficer** [comment]
I found the culprit, at least - it's an incompatibility with SimpleSidearms. My mods (in order):

- Harmony 1.0.4.0
- BetterLoading 3.1.1.0
- Core 1.2
- Mod Manager 3.8.1038
- HugsLib 1.2.0.1
- SimpleSidearsm 1.4.5.0 (at least those are the versions Mod Manager displays, it's actually [v1.5.3](https://github.com/PeteTimesSix/SimpleSidearms/releases/tag/v1.5.3))
